$ErrorActionPreference = 'Stop'
$root = Resolve-Path (Join-Path $PSScriptRoot '..\..\..')
function Read-Source([string]$Path) { Get-Content -Raw (Join-Path $root $Path) }
function Assert-Match([string]$Text, [string]$Pattern, [string]$Message) {
	if ($Text -notmatch $Pattern) { throw $Message }
}

$cvars = Read-Source 'source/common/rendering/nri/renderer/nri_cvars.cpp'
$settings = Read-Source 'source/common/rendering/nri/renderer/nri_renderer_settings.cpp'
$settingsHeader = Read-Source 'source/common/rendering/nri/renderer/nri_renderer_settings.h'
$config = Read-Source 'source/core/gameconfigfile.cpp'
$gameControl = Read-Source 'source/core/gamecontrol.cpp'
$scheduler = Read-Source 'source/common/rendering/nri/renderer/nri_smoke_work_scheduler.cpp'
$schedulerHeader = Read-Source 'source/common/rendering/nri/renderer/nri_smoke_work_scheduler.h'
$runtime = Read-Source 'source/common/rendering/nri/renderer/nri_smoke.cpp'
$menu = Read-Source 'wadsrc/static/menudef.txt'
$seed = Read-Source 'source/common/rendering/nri/shaders/SmokeGridLightSeed.cs.hlsl'

Assert-Match $cvars 'CVAR\(Int, nri_ptsmokeworkprofile, 2, CVAR_ARCHIVE \| CVAR_GLOBALCONFIG\)' 'Work profile must be archived and default to Medium.'
Assert-Match $cvars 'CUSTOM_CVAR\(Bool, nri_ptsmoke, true, CVAR_ARCHIVE \| CVAR_GLOBALCONFIG\)' 'Smoke must be archived and default on.'
Assert-Match $cvars 'CVAR\(Bool, nri_ptsmokedormantgrid, true, CVAR_ARCHIVE \| CVAR_GLOBALCONFIG\)' 'Bounded dormant smoke residency must be enabled by default.'
Assert-Match $settingsHeader 'bool enabled = true;' 'Captured smoke settings must agree with the master CVar default.'
Assert-Match $settingsHeader 'bool dormantGrid = true;' 'Captured smoke settings must agree with the dormant residency CVar default.'
Assert-Match $settingsHeader 'uint32_t workProfile = 2;' 'Captured smoke settings must agree with the Medium CVar default.'
Assert-Match $settings 'settings\.workProfile\s*=\s*\(uint32_t\)std::max\(\(int\)nri_ptsmokeworkprofile,\s*0\)' 'Captured settings must carry the requested profile.'
Assert-Match $menu 'Option\s+"Smoke Quality",\s*"nri_ptsmokeworkprofile",\s*"NRISmokeWorkProfile"' 'Video options must expose Smoke Quality.'
Assert-Match $cvars 'Smoke is very taxing on your GPU, especially at Ultra settings' 'The enabled smoke warning must identify the GPU cost and call out Ultra settings.'
if ($cvars -match 'Smoke is experimental') { throw 'The production smoke warning must not describe smoke as experimental.' }
Assert-Match $menu 'OptionValue NRISmokeWorkProfile[\s\S]*0, "Ultra"[\s\S]*1, "High"[\s\S]*2, "Medium"[\s\S]*3, "Low"' 'Menu values must match the runtime profile ABI.'
Assert-Match $schedulerHeader 'Reference\s*=\s*0[\s\S]*High\s*=\s*1[\s\S]*Medium\s*=\s*2[\s\S]*Low\s*=\s*3' 'Profiles must preserve the archived numeric ABI.'
Assert-Match $scheduler 'NRISmokeWorkProfile::Reference[\s\S]*return "ultra"' 'Profile zero diagnostics must use the Ultra name.'
Assert-Match $schedulerHeader 'no GPU[\s\S]*timing[\s\S]*renderer-headroom[\s\S]*target-frame-time[\s\S]*predicted-cost' 'Scheduler contract must reject adaptive timing inputs explicitly.'
Assert-Match $scheduler 'NRISmokeWorkProfile::High[\s\S]*emissionCommands = 128u[\s\S]*NRISmokeWorkProfile::Medium[\s\S]*emissionCommands = 32u[\s\S]*NRISmokeWorkProfile::Low[\s\S]*emissionCommands = 16u' 'Static profile command tables are missing.'
Assert-Match $scheduler 'NRISmokeWorkProfile::High[\s\S]*froxelPixelSize = 16u[\s\S]*froxelDepth = 48u' 'High static froxel table is missing.'
Assert-Match $scheduler 'NRISmokeWorkProfile::Medium[\s\S]*froxelPixelSize = 24u[\s\S]*froxelDepth = 32u' 'Medium static froxel table is missing.'
Assert-Match $scheduler 'NRISmokeWorkProfile::Low[\s\S]*froxelPixelSize = 32u[\s\S]*froxelDepth = 24u' 'Low static froxel table is missing.'
Assert-Match $scheduler 'NRISmokeWorkProfile::Low[\s\S]*emissiveLights = 0u[\s\S]*emissiveBackend = 0u[\s\S]*lightSamples = 1u[\s\S]*maximumLightCandidates = 4u' 'Low static lighting table is missing.'
Assert-Match $schedulerHeader 'admissionBrickRequests = Unrestricted[\s\S]*depositionCellVisits = Unrestricted[\s\S]*projectionWorkUnits = Unrestricted[\s\S]*materializedFroxels = Unrestricted[\s\S]*worldLinkRays = Unrestricted[\s\S]*directReceiverSamples = Unrestricted' 'Unsupported GPU families must not advertise fake caps.'
Assert-Match $scheduler 'NRISmokeWorkProfile::High[\s\S]*dormantArchives = 8u[\s\S]*dormantPromotions = 8u[\s\S]*dormantEvolution = 32u[\s\S]*NRISmokeWorkProfile::Medium[\s\S]*dormantArchives = 4u[\s\S]*dormantPromotions = 4u[\s\S]*dormantEvolution = 16u[\s\S]*NRISmokeWorkProfile::Low[\s\S]*dormantArchives = 2u[\s\S]*dormantPromotions = 2u[\s\S]*dormantEvolution = 8u' 'Dormant residency must use immutable profile quantities.'
Assert-Match $runtime 'maximumCommands\s*=\s*std::min\(kMaxCommands, workTable\.emissionCommands\)' 'Emission transport must apply the fixed profile quantity.'
Assert-Match $runtime 'mPromptFallback\.Prepare\([\s\S]*workTable\.firstUseSources' 'Prompt first-use must apply the fixed profile quantity.'
Assert-Match $runtime 'std::min\(dueSubsteps, workTable\.simulationSubsteps\)[\s\S]*RecordSimulation\(dueSubsteps, substeps, debtSubsteps\)' 'Simulation must cap work while retaining explicit debt.'
Assert-Match $runtime 'workSchedule\.table\.froxelPixelSize[\s\S]*mSettings\.froxelPixelSize[\s\S]*workSchedule\.table\.froxelDepth[\s\S]*mSettings\.froxelDepth' 'Profiles must resolve static froxel dimensions before resource preparation.'
Assert-Match $runtime 'workSchedule\.table\.emissiveLights[\s\S]*mSettings\.emissiveLights[\s\S]*workSchedule\.table\.lightSamples[\s\S]*mSettings\.lightSamples' 'Profiles must resolve static lighting quantities before resource preparation.'
Assert-Match $seed 'NRI_SMOKE_GRID_LIGHT_WORK_LIMITED[\s\S]*SmokeGridLightClaimNewInvalid[\s\S]*SmokeGridLightClaimMaintenance' 'Static profiles must activate both existing radiance ticket lanes.'
Assert-Match $runtime 'PERF pt smoke schedule NRI:[\s\S]*unsupported_unrestricted=%u' 'Compact telemetry must publish the fixed table and unsupported sentinel.'
Assert-Match $config '#define\s+LASTRUNVERSION\s+"9"' 'The smoke migration must advance the archived config version.'
Assert-Match $config 'if\s*\(last\s*<\s*9\)[\s\S]*FindCVar\("nri_ptsmoke"[\s\S]*SetGenericRep\(true,\s*CVAR_Bool\)' 'Prior-install smoke settings must be forced on once.'
Assert-Match $gameControl 'G_LoadConfig\(\);[\s\S]*V_Init2\(\);[\s\S]*G_ReadConfig\(currentGame\.GetChars\(\)\);' 'Archived smoke migration must run before normal command-line settings.'

Write-Host 'Smoke work profile structural tests passed.'
